language: c
sudo: required
script: bash -ex .travis-ci.sh
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
notifications:
  email:
  - christophe@raffalli.eu
